In [ ]:
!unzip /content/archive.zip

Archive:  /content/archive.zip
  inflating: test_tweets_anuFYb8.csv  
  inflating: train_E6oV3lV.csv       


Import the required libraries

In [ ]:
import pandas as pd
import numpy as np
from wordcloud import WordCloud
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

Load the train and test data

In [ ]:
train = pd.read_csv('/content/train_E6oV3lV.csv')
test = pd.read_csv('/content/test_tweets_anuFYb8.csv')

Audit the data

In [ ]:
train.head(10)

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation
5   6      0  [2/2] huge fan fare and big talking before the...
6   7      0   @user camping tomorrow @user @user @user @use...
7   8      0  the next school year is the year for exams.ðŸ˜...
8   9      0  we won!!! love the land!!! #allin #cavs #champ...
9  10      0   @user @user welcome here !  i'm   it's so #gr...

In [ ]:
train.shape

(31962, 3)

In [ ]:
train['label'].value_counts()

0    29720
1     2242
Name: label, dtype: int64

In [ ]:
train.dtypes

id        int64
label     int64
tweet    object
dtype: object

In [ ]:
Y = train['label']

In [ ]:
cv = CountVectorizer(stop_words={'english'})
X = cv.fit_transform(train['tweet'])

In [ ]:
print(X.shape)

(31962, 41391)


X is huge and it si compreseed and stored as a sparse matrix,so X.head() will not work

In [ ]:
type(X)

scipy.sparse.csr.csr_matrix

In [ ]:
X

<31962x41391 sparse matrix of type '<class 'numpy.int64'>'
	with 366847 stored elements in Compressed Sparse Row format>

In [ ]:
cv.get_feature_names()

['00',
 '000',
 '000001',
 '001',
 '0099',
 '00am',
 '00h30',
 '00pm',
 '01',
 '0115',
 '0161',
 '01926889917',
 '02',
 '0266808099',
 '03',
 '030916',
 '03111880779',
 '033',
 '0345',
 '039',
 '04',
 '0450',
 '04pm',
 '05',
 '0506823156',
 '05pm',
 '06',
 '0606',
 '0608',
 '0609',
 '0610',
 '0612',
 '0613',
 '0616',
 '0616ç',
 '0617',
 '0618',
 '0618â',
 '0619',
 '0620',
 '0622',
 '064',
 '07',
 '07788427999',
 '08',
 '0830',
 '09',
 '09053111156',
 '095m',
 '0k',
 '0shares',
 '0tolerancemovie',
 '0ï',
 '0ð',
 '10',
 '100',
 '1000',
 '10003',
 '10007',
 '1000gifts',
 '1000th',
 '1000x',
 '1000â',
 '1001',
 '10014',
 '10021',
 '10025',
 '10040',
 '100d',
 '100daysofcode',
 '100daysofpigpaintings',
 '100daysoftea',
 '100faces',
 '100happydays',
 '100happydaysâ',
 '100happysongs',
 '100k',
 '100ml',
 '100â',
 '101',
 '1014',
 '101dalmatians',
 '101daysofsmiles',
 '101ð',
 '1024x589',
 '10353',
 '104',
 '105',
 '105kg',
 '106',
 '107',
 '1070',
 '1080',
 '109',
 '10a',
 '10am',
 '10days',

In [ ]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


Split data into train, test split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size= 0.2, random_state = 123)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(25569, 41391)
(6393, 41391)
(25569,)
(6393,)


In [ ]:
svc = SVC(verbose=True)
svc.fit(x_train,y_train)

[LibSVM]

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=True)

In [ ]:
preds_svc = svc.predict(x_test)

Evalution of the model

In [ ]:
acc_score_svc = accuracy_score(y_test,preds_svc)
confu_matrx = confusion_matrix(y_test,preds_svc)
classification_report = classification_report(y_test, preds_svc)
print('The Accuracy of the model is: ', acc_score_svc)
print(confu_matrx)
print(classification_report)

The Accuracy of the model is:  0.9558892538714219
[[5956    4]
 [ 278  155]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      5960
           1       0.97      0.36      0.52       433

    accuracy                           0.96      6393
   macro avg       0.97      0.68      0.75      6393
weighted avg       0.96      0.96      0.95      6393



TF-IDF

In [ ]:
vect = TfidfVectorizer(stop_words={'english'})
x_tfidf = vect.fit_transform(train['tweet'])

In [ ]:
x_tfidf.shape

(31962, 41391)

In [ ]:
x_train_tf, x_test_tf, y_train_tf, y_test_tf = train_test_split(x_tfidf, Y, test_size= 0.2, random_state = 123)
print(x_train_tf.shape)
print(x_test_tf.shape)
print(y_train_tf.shape)
print(y_test_tf.shape)

(25569, 41391)
(6393, 41391)
(25569,)
(6393,)


Apply svm with tfidf

In [ ]:
svc_tfidf = SVC(C=2,verbose=True)
svc_tfidf.fit(x_train_tf,y_train_tf)

[LibSVM]

SVC(C=1.5, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=True)

In [ ]:
preds_svc_tf = svc_tfidf.predict(x_test_tf)

In [ ]:
preds_svc_tf

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_test_tf

20284    0
12981    0
10224    0
15932    0
12152    0
        ..
24447    0
25413    0
26096    0
988      0
4621     0
Name: label, Length: 6393, dtype: int64

In [ ]:
acc_score_svc_tf = accuracy_score(y_test_tf,preds_svc_tf)
print('The Accuracy of the model is: ', acc_score_svc_tf)

The Accuracy of the model is:  0.9640231503206632


In [ ]:
confu_matrx_tf = confusion_matrix(y_test_tf,preds_svc_tf)
print(confu_matrx_tf)

[[5954    6]
 [ 224  209]]


In [ ]:
classifi_report_tf = classification_report(y_test_tf,preds_svc_tf)
print(classifi_report_tf)

TypeError: ignored

Multi layer perceptron

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(50,50,50), max_iter=600,random_state = 42)
mlp.fit(x_train_tf, y_train_tf)
preds_mlp = mlp.predict(x_test_tf)

#print(clrep_mlp)

TypeError: ignored

In [ ]:
acc_mlp = accuracy_score(y_test_tf, preds_mlp)
confusion_matrix_mlp = confusion_matrix(y_test_tf, preds_mlp)

print('Accuracy score for MLP is: ', acc_mlp)
print(confusion_matrix_mlp)

Accuracy score for MLP is:  0.9597997810104802
[[5855  105]
 [ 152  281]]
